bump libevent to 2.1.12-stable
On Debian 12 Bookworm, the project fails to build due to the following error during the build of `libevent`:

```
/usr/bin/ld: /usr/bin/ld: ./.libs/libevent.a(evutil_rand.o): in function `evutil_secure_rng_add_bytes':
/daemon/depends/work/build/x86_64-unknown-linux-gnu/libevent/2.1.8-8948de65303/evutil_rand.c:198: undefined reference to `arc4random_addrandom'
...
collect2: error: ld returned 1 exit status
...
make: *** [funcs.mk:260: /daemon/depends/work/build/x86_64-unknown-linux-gnu/libevent/2.1.8-8948de65303/./.stamp_built] Error 2
```

This fix resolves the issue.